on: [push] # 保存ボタンが押されたらスタート
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # 第3章で作った鍵を使う
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'taro-webapp-cicd'
